/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module iiitb_aclock(reset, clk, H_in1, H_in0, M_in1, M_in0, LD_time, LD_alarm, STOP_al, AL_ON, Alarm, H_out1, H_out0, M_out1, M_out0, S_out1, S_out0);
  wire _000_;
  wire [3:0] _001_;
  wire [1:0] _002_;
  wire [3:0] _003_;
  wire [3:0] _004_;
  wire [3:0] _005_;
  wire [3:0] _006_;
  wire _007_;
  wire [3:0] _008_;
  wire [5:0] _009_;
  wire [5:0] _010_;
  wire [5:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  input AL_ON;
  output Alarm;
  input [3:0] H_in0;
  input [1:0] H_in1;
  output [3:0] H_out0;
  output [1:0] H_out1;
  input LD_alarm;
  input LD_time;
  input [3:0] M_in0;
  input [3:0] M_in1;
  output [3:0] M_out0;
  output [3:0] M_out1;
  input STOP_al;
  output [3:0] S_out0;
  output [3:0] S_out1;
  wire [3:0] a_hour0;
  wire [1:0] a_hour1;
  wire [3:0] a_min0;
  wire [3:0] a_min1;
  wire [3:0] a_sec0;
  wire [3:0] a_sec1;
  wire [3:0] c_hour0;
  wire [1:0] c_hour1;
  wire [3:0] c_min0;
  wire [2:0] c_min1;
  wire [3:0] c_sec0;
  wire [3:0] c_sec1;
  input clk;
  wire clk_1s;
  input reset;
  wire [3:0] tmp_1s;
  wire [5:0] tmp_hour;
  wire [5:0] tmp_minute;
  wire [5:0] tmp_second;
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(reset),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _283_ (
    .A(_012_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__clkinv_1 _284_ (
    .A(tmp_minute[5]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__clkinv_1 _285_ (
    .A(a_sec1[0]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__clkinv_1 _286_ (
    .A(a_sec1[1]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(M_in0[3]),
    .B(M_in1[2]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__xnor2_1 _288_ (
    .A(M_in1[3]),
    .B(_080_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nand2_1 _289_ (
    .A(M_in1[1]),
    .B(_081_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__xor2_1 _290_ (
    .A(M_in1[2]),
    .B(_082_),
    .X(_083_)
  );
  sky130_fd_sc_hd__a31oi_1 _291_ (
    .A1(M_in0[3]),
    .A2(M_in1[2]),
    .A3(M_in1[3]),
    .B1(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _292_ (
    .A(M_in0[2]),
    .B(M_in1[1]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__xor2_1 _293_ (
    .A(M_in0[3]),
    .B(M_in1[2]),
    .X(_086_)
  );
  sky130_fd_sc_hd__nand3_1 _294_ (
    .A(M_in0[2]),
    .B(M_in1[1]),
    .C(_086_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _295_ (
    .A(M_in1[3]),
    .B(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__xnor2_1 _296_ (
    .A(M_in1[1]),
    .B(_081_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(_087_),
    .A2(_089_),
    .B1(_088_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__xor2_1 _298_ (
    .A(M_in0[2]),
    .B(M_in1[1]),
    .X(_091_)
  );
  sky130_fd_sc_hd__and3_1 _299_ (
    .A(M_in0[1]),
    .B(M_in1[0]),
    .C(_091_),
    .X(_092_)
  );
  sky130_fd_sc_hd__xnor2_1 _300_ (
    .A(_085_),
    .B(_086_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ai_0 _301_ (
    .A1(_092_),
    .A2(_093_),
    .B1(M_in1[0]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__clkinv_1 _302_ (
    .A(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _303_ (
    .A1(_090_),
    .A2(_095_),
    .B1(_088_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__xnor2_1 _304_ (
    .A(_084_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2b_1 _305_ (
    .A_N(_097_),
    .B(reset),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _306_ (
    .A(_090_),
    .B(_095_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(reset),
    .B(_098_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _308_ (
    .A1(_092_),
    .A2(_093_),
    .B1(_094_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _309_ (
    .A(M_in1[0]),
    .B(_093_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(_099_),
    .B(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__or2_0 _311_ (
    .A(_075_),
    .B(_101_),
    .X(_036_)
  );
  sky130_fd_sc_hd__a21oi_1 _312_ (
    .A1(M_in0[1]),
    .A2(M_in1[0]),
    .B1(_091_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(_092_),
    .B(_102_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2b_1 _314_ (
    .A_N(_103_),
    .B(reset),
    .Y(_034_)
  );
  sky130_fd_sc_hd__xor2_1 _315_ (
    .A(M_in0[1]),
    .B(M_in1[0]),
    .X(_104_)
  );
  sky130_fd_sc_hd__nand2b_1 _316_ (
    .A_N(_104_),
    .B(reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2b_1 _317_ (
    .A_N(M_in0[0]),
    .B(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(H_in1[0]),
    .B(H_in0[3]),
    .Y(_105_)
  );
  sky130_fd_sc_hd__xor2_1 _319_ (
    .A(H_in1[1]),
    .B(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(H_in1[1]),
    .B(H_in0[2]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__xnor2_1 _321_ (
    .A(H_in1[0]),
    .B(H_in0[3]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(H_in1[0]),
    .B(H_in0[1]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__xnor2_1 _324_ (
    .A(H_in1[1]),
    .B(H_in0[2]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_110_),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(_112_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__xor2_1 _327_ (
    .A(_107_),
    .B(_108_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a21oi_1 _328_ (
    .A1(_112_),
    .A2(_114_),
    .B1(_109_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_106_),
    .B(_115_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a31oi_1 _330_ (
    .A1(H_in1[0]),
    .A2(H_in1[1]),
    .A3(H_in0[3]),
    .B1(_116_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _331_ (
    .A(reset),
    .B(_117_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__xor2_1 _332_ (
    .A(_106_),
    .B(_115_),
    .X(_118_)
  );
  sky130_fd_sc_hd__nand2b_1 _333_ (
    .A_N(_118_),
    .B(reset),
    .Y(_026_)
  );
  sky130_fd_sc_hd__xnor2_1 _334_ (
    .A(_112_),
    .B(_114_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(reset),
    .B(_119_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(_110_),
    .B(_111_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _337_ (
    .A(_113_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(reset),
    .B(_121_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _339_ (
    .A(H_in1[0]),
    .B(H_in0[1]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _340_ (
    .A(reset),
    .B(_122_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2b_1 _341_ (
    .A_N(H_in0[0]),
    .B(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(tmp_hour[1]),
    .B(tmp_hour[0]),
    .Y(_123_)
  );
  sky130_fd_sc_hd__or2_0 _343_ (
    .A(tmp_hour[1]),
    .B(tmp_hour[0]),
    .X(_124_)
  );
  sky130_fd_sc_hd__nor2b_1 _344_ (
    .A(_013_),
    .B_N(tmp_hour[4]),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a311oi_1 _345_ (
    .A1(_076_),
    .A2(tmp_hour[4]),
    .A3(_124_),
    .B1(_125_),
    .C1(tmp_hour[5]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand4b_1 _346_ (
    .A_N(tmp_hour[3]),
    .B(tmp_hour[2]),
    .C(tmp_hour[4]),
    .D(_123_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__and2_0 _347_ (
    .A(_126_),
    .B(_127_),
    .X(_128_)
  );
  sky130_fd_sc_hd__clkinv_1 _348_ (
    .A(_128_),
    .Y(H_out1[1])
  );
  sky130_fd_sc_hd__nor2_1 _349_ (
    .A(tmp_minute[0]),
    .B(tmp_minute[1]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__o21ai_0 _350_ (
    .A1(tmp_minute[0]),
    .A2(tmp_minute[1]),
    .B1(tmp_minute[3]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nor2b_1 _351_ (
    .A(tmp_minute[4]),
    .B_N(tmp_minute[5]),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nand2_1 _352_ (
    .A(tmp_minute[3]),
    .B(tmp_minute[2]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a31oi_1 _353_ (
    .A1(_130_),
    .A2(_131_),
    .A3(_132_),
    .B1(_016_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__nor2b_1 _354_ (
    .A(tmp_minute[2]),
    .B_N(tmp_minute[3]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a31oi_1 _355_ (
    .A1(_129_),
    .A2(_131_),
    .A3(_134_),
    .B1(_133_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(tmp_minute[5]),
    .B(tmp_minute[4]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o21bai_1 _357_ (
    .A1(tmp_minute[0]),
    .A2(tmp_minute[1]),
    .B1_N(_015_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__or4b_1 _358_ (
    .A(tmp_minute[0]),
    .B(tmp_minute[1]),
    .C(tmp_minute[3]),
    .D_N(tmp_minute[2]),
    .X(_138_)
  );
  sky130_fd_sc_hd__a41oi_1 _359_ (
    .A1(_077_),
    .A2(_014_),
    .A3(_137_),
    .A4(_138_),
    .B1(_136_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__and2_0 _360_ (
    .A(tmp_minute[0]),
    .B(tmp_minute[1]),
    .X(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(tmp_minute[0]),
    .B(tmp_minute[1]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__a21o_1 _362_ (
    .A1(_134_),
    .A2(_141_),
    .B1(_014_),
    .X(_142_)
  );
  sky130_fd_sc_hd__nand3b_1 _363_ (
    .A_N(tmp_minute[0]),
    .B(tmp_minute[1]),
    .C(_134_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a31oi_1 _364_ (
    .A1(_136_),
    .A2(_142_),
    .A3(_143_),
    .B1(_139_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(tmp_minute[1]),
    .B(tmp_minute[4]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__o21ai_0 _366_ (
    .A1(_132_),
    .A2(_145_),
    .B1(_077_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21ai_0 _367_ (
    .A1(_144_),
    .A2(_146_),
    .B1(_135_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o311ai_0 _368_ (
    .A1(tmp_minute[1]),
    .A2(tmp_minute[3]),
    .A3(tmp_minute[2]),
    .B1(tmp_minute[5]),
    .C1(tmp_minute[4]),
    .Y(_148_)
  );
  sky130_fd_sc_hd__clkinv_1 _369_ (
    .A(_148_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _370_ (
    .A(_147_),
    .B(_148_),
    .Y(M_out1[0])
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_139_),
    .B(_146_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a311oi_1 _372_ (
    .A1(_129_),
    .A2(_131_),
    .A3(_134_),
    .B1(_149_),
    .C1(_133_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__clkinv_1 _373_ (
    .A(_151_),
    .Y(M_out1[2])
  );
  sky130_fd_sc_hd__o21ai_0 _374_ (
    .A1(_139_),
    .A2(_146_),
    .B1(_151_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__clkinv_1 _375_ (
    .A(_152_),
    .Y(M_out1[1])
  );
  sky130_fd_sc_hd__nand2_1 _376_ (
    .A(tmp_second[5]),
    .B(tmp_second[4]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__o21ai_0 _377_ (
    .A1(tmp_second[3]),
    .A2(tmp_second[4]),
    .B1(tmp_second[5]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__clkinv_1 _378_ (
    .A(_154_),
    .Y(S_out1[2])
  );
  sky130_fd_sc_hd__o21a_1 _379_ (
    .A1(tmp_second[2]),
    .A2(tmp_second[3]),
    .B1(tmp_second[4]),
    .X(_155_)
  );
  sky130_fd_sc_hd__nand4b_1 _380_ (
    .A_N(tmp_second[5]),
    .B(tmp_second[3]),
    .C(tmp_second[2]),
    .D(tmp_second[1]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o22ai_1 _381_ (
    .A1(tmp_second[5]),
    .A2(_155_),
    .B1(_156_),
    .B2(tmp_second[0]),
    .Y(_157_)
  );
  sky130_fd_sc_hd__or2_0 _382_ (
    .A(tmp_second[1]),
    .B(tmp_second[2]),
    .X(_158_)
  );
  sky130_fd_sc_hd__nor2b_1 _383_ (
    .A(tmp_second[4]),
    .B_N(tmp_second[3]),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21o_1 _384_ (
    .A1(tmp_second[0]),
    .A2(tmp_second[1]),
    .B1(tmp_second[2]),
    .X(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _385_ (
    .A(tmp_second[3]),
    .B(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__and4_1 _386_ (
    .A(tmp_second[0]),
    .B(tmp_second[1]),
    .C(tmp_second[2]),
    .D(tmp_second[3]),
    .X(_162_)
  );
  sky130_fd_sc_hd__a21oi_1 _387_ (
    .A1(tmp_second[4]),
    .A2(_162_),
    .B1(tmp_second[5]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a221o_1 _388_ (
    .A1(_158_),
    .A2(_159_),
    .B1(_162_),
    .B2(tmp_second[4]),
    .C1(tmp_second[5]),
    .X(_164_)
  );
  sky130_fd_sc_hd__a21oi_1 _389_ (
    .A1(tmp_second[4]),
    .A2(_157_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _390_ (
    .A(tmp_second[3]),
    .B(_158_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__o22ai_1 _391_ (
    .A1(S_out1[2]),
    .A2(_165_),
    .B1(_166_),
    .B2(_153_),
    .Y(S_out1[0])
  );
  sky130_fd_sc_hd__o21ai_0 _392_ (
    .A1(tmp_second[5]),
    .A2(_155_),
    .B1(_154_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__clkinv_1 _393_ (
    .A(_167_),
    .Y(S_out1[1])
  );
  sky130_fd_sc_hd__a21oi_1 _394_ (
    .A1(_147_),
    .A2(_148_),
    .B1(tmp_minute[1]),
    .Y(_168_)
  );
  sky130_fd_sc_hd__xor2_1 _395_ (
    .A(_015_),
    .B(_152_),
    .X(_169_)
  );
  sky130_fd_sc_hd__xor2_1 _396_ (
    .A(_168_),
    .B(_169_),
    .X(M_out0[2])
  );
  sky130_fd_sc_hd__o21ai_0 _397_ (
    .A1(tmp_minute[1]),
    .A2(_169_),
    .B1(M_out1[0]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__o21ai_0 _398_ (
    .A1(tmp_minute[2]),
    .A2(_150_),
    .B1(_151_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__xnor2_1 _399_ (
    .A(_014_),
    .B(_171_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xnor2_1 _400_ (
    .A(_170_),
    .B(_172_),
    .Y(M_out0[3])
  );
  sky130_fd_sc_hd__nor2b_1 _401_ (
    .A(tmp_hour[2]),
    .B_N(tmp_hour[3]),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nand2_1 _402_ (
    .A(tmp_hour[1]),
    .B(tmp_hour[0]),
    .Y(_174_)
  );
  sky130_fd_sc_hd__a21oi_1 _403_ (
    .A1(_173_),
    .A2(_174_),
    .B1(_013_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__and3b_1 _404_ (
    .A_N(tmp_hour[0]),
    .B(_173_),
    .C(tmp_hour[1]),
    .X(_176_)
  );
  sky130_fd_sc_hd__or2_0 _405_ (
    .A(tmp_hour[4]),
    .B(tmp_hour[5]),
    .X(_177_)
  );
  sky130_fd_sc_hd__o311a_1 _406_ (
    .A1(_175_),
    .A2(_176_),
    .A3(_177_),
    .B1(_127_),
    .C1(_126_),
    .X(H_out1[0])
  );
  sky130_fd_sc_hd__nand2_1 _407_ (
    .A(_017_),
    .B(H_out1[0]),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand3_1 _408_ (
    .A(tmp_hour[2]),
    .B(_126_),
    .C(_127_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o21ai_0 _409_ (
    .A1(tmp_hour[2]),
    .A2(_126_),
    .B1(_179_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _410_ (
    .A(_178_),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__xnor2_1 _411_ (
    .A(_178_),
    .B(_180_),
    .Y(H_out0[2])
  );
  sky130_fd_sc_hd__nand2b_1 _412_ (
    .A_N(tmp_second[1]),
    .B(S_out1[0]),
    .Y(_182_)
  );
  sky130_fd_sc_hd__xor2_1 _413_ (
    .A(tmp_second[2]),
    .B(_182_),
    .X(_183_)
  );
  sky130_fd_sc_hd__maj3_1 _414_ (
    .A(tmp_second[2]),
    .B(_167_),
    .C(_182_),
    .X(_184_)
  );
  sky130_fd_sc_hd__a21oi_1 _415_ (
    .A1(tmp_second[5]),
    .A2(tmp_second[4]),
    .B1(tmp_second[3]),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21oi_1 _416_ (
    .A1(tmp_second[3]),
    .A2(tmp_second[5]),
    .B1(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xor2_1 _417_ (
    .A(S_out1[0]),
    .B(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__and2_0 _418_ (
    .A(_184_),
    .B(_187_),
    .X(S_out0[3])
  );
  sky130_fd_sc_hd__xnor2_1 _419_ (
    .A(a_sec0[3]),
    .B(S_out0[3]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__xnor2_1 _420_ (
    .A(a_min0[3]),
    .B(M_out0[3]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__xor2_1 _421_ (
    .A(tmp_minute[1]),
    .B(M_out1[0]),
    .X(M_out0[1])
  );
  sky130_fd_sc_hd__xnor2_1 _422_ (
    .A(a_min0[1]),
    .B(M_out0[1]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xor2_1 _423_ (
    .A(a_hour0[2]),
    .B(H_out0[2]),
    .X(_191_)
  );
  sky130_fd_sc_hd__xor2_1 _424_ (
    .A(a_hour1[0]),
    .B(H_out1[0]),
    .X(_192_)
  );
  sky130_fd_sc_hd__o21ai_0 _425_ (
    .A1(a_sec1[2]),
    .A2(_154_),
    .B1(_079_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nand2_1 _426_ (
    .A(a_sec1[1]),
    .B(S_out1[1]),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21ai_0 _427_ (
    .A1(S_out1[1]),
    .A2(_193_),
    .B1(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__xnor2_1 _428_ (
    .A(tmp_minute[0]),
    .B(a_min0[0]),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(a_sec1[3]),
    .B(a_min1[3]),
    .Y(_197_)
  );
  sky130_fd_sc_hd__nand3_1 _430_ (
    .A(AL_ON),
    .B(_196_),
    .C(_197_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__xor2_1 _431_ (
    .A(tmp_second[0]),
    .B(a_sec0[0]),
    .X(_199_)
  );
  sky130_fd_sc_hd__xor2_1 _432_ (
    .A(tmp_hour[0]),
    .B(a_hour0[0]),
    .X(_200_)
  );
  sky130_fd_sc_hd__nor2_1 _433_ (
    .A(_199_),
    .B(_200_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__xnor2_1 _434_ (
    .A(_017_),
    .B(H_out1[0]),
    .Y(H_out0[1])
  );
  sky130_fd_sc_hd__xor2_1 _435_ (
    .A(tmp_second[1]),
    .B(S_out1[0]),
    .X(S_out0[1])
  );
  sky130_fd_sc_hd__xor2_1 _436_ (
    .A(a_sec0[1]),
    .B(S_out0[1]),
    .X(_202_)
  );
  sky130_fd_sc_hd__a21oi_1 _437_ (
    .A1(_012_),
    .A2(H_out1[1]),
    .B1(H_out1[0]),
    .Y(_203_)
  );
  sky130_fd_sc_hd__xnor2_1 _438_ (
    .A(_013_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__xnor2_1 _439_ (
    .A(_181_),
    .B(_204_),
    .Y(H_out0[3])
  );
  sky130_fd_sc_hd__xnor3_1 _440_ (
    .A(a_hour0[3]),
    .B(_181_),
    .C(_204_),
    .X(_205_)
  );
  sky130_fd_sc_hd__xnor2_1 _441_ (
    .A(S_out1[1]),
    .B(_183_),
    .Y(S_out0[2])
  );
  sky130_fd_sc_hd__and2_0 _442_ (
    .A(a_min0[2]),
    .B(M_out0[2]),
    .X(_206_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(a_min0[2]),
    .B(M_out0[2]),
    .Y(_207_)
  );
  sky130_fd_sc_hd__xnor2_1 _444_ (
    .A(a_sec0[2]),
    .B(S_out0[2]),
    .Y(_208_)
  );
  sky130_fd_sc_hd__xor2_1 _445_ (
    .A(a_min1[0]),
    .B(M_out1[0]),
    .X(_209_)
  );
  sky130_fd_sc_hd__a221o_1 _446_ (
    .A1(a_hour1[1]),
    .A2(_128_),
    .B1(_154_),
    .B2(a_sec1[2]),
    .C1(_198_),
    .X(_210_)
  );
  sky130_fd_sc_hd__a21oi_1 _447_ (
    .A1(a_min1[1]),
    .A2(_152_),
    .B1(_192_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__o221ai_1 _448_ (
    .A1(a_hour1[1]),
    .A2(_128_),
    .B1(_151_),
    .B2(a_min1[2]),
    .C1(_201_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _449_ (
    .A1(_078_),
    .A2(S_out1[0]),
    .B1(_212_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__o2111ai_1 _450_ (
    .A1(a_min1[1]),
    .A2(_152_),
    .B1(_195_),
    .C1(_211_),
    .D1(_213_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__a2111oi_0 _451_ (
    .A1(a_min1[2]),
    .A2(_151_),
    .B1(_209_),
    .C1(_210_),
    .D1(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__xnor2_1 _452_ (
    .A(a_hour0[1]),
    .B(H_out0[1]),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o21ai_0 _453_ (
    .A1(_078_),
    .A2(S_out1[0]),
    .B1(_216_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nor4_1 _454_ (
    .A(_191_),
    .B(_202_),
    .C(_205_),
    .D(_217_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__o2111a_1 _455_ (
    .A1(_206_),
    .A2(_207_),
    .B1(_215_),
    .C1(_218_),
    .D1(_190_),
    .X(_219_)
  );
  sky130_fd_sc_hd__a41oi_1 _456_ (
    .A1(_188_),
    .A2(_189_),
    .A3(_208_),
    .A4(_219_),
    .B1(Alarm),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nor2_1 _457_ (
    .A(STOP_al),
    .B(_220_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__a21o_1 _458_ (
    .A1(tmp_1s[2]),
    .A2(tmp_1s[1]),
    .B1(tmp_1s[3]),
    .X(_007_)
  );
  sky130_fd_sc_hd__o21a_1 _459_ (
    .A1(tmp_1s[2]),
    .A2(tmp_1s[1]),
    .B1(tmp_1s[3]),
    .X(_221_)
  );
  sky130_fd_sc_hd__nand2b_1 _460_ (
    .A_N(_221_),
    .B(tmp_1s[0]),
    .Y(_008_[0])
  );
  sky130_fd_sc_hd__nor2_1 _461_ (
    .A(tmp_1s[0]),
    .B(tmp_1s[1]),
    .Y(_222_)
  );
  sky130_fd_sc_hd__and2_0 _462_ (
    .A(tmp_1s[0]),
    .B(tmp_1s[1]),
    .X(_223_)
  );
  sky130_fd_sc_hd__nor3_1 _463_ (
    .A(_221_),
    .B(_222_),
    .C(_223_),
    .Y(_008_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _464_ (
    .A1(tmp_1s[2]),
    .A2(_223_),
    .B1(tmp_1s[3]),
    .Y(_224_)
  );
  sky130_fd_sc_hd__o21a_1 _465_ (
    .A1(tmp_1s[2]),
    .A2(_223_),
    .B1(_224_),
    .X(_008_[2])
  );
  sky130_fd_sc_hd__nor2_1 _466_ (
    .A(_221_),
    .B(_224_),
    .Y(_008_[3])
  );
  sky130_fd_sc_hd__mux2_1 _467_ (
    .A0(a_min0[0]),
    .A1(M_in0[0]),
    .S(LD_alarm),
    .X(_003_[0])
  );
  sky130_fd_sc_hd__mux2_1 _468_ (
    .A0(a_min0[1]),
    .A1(M_in0[1]),
    .S(LD_alarm),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__mux2_1 _469_ (
    .A0(a_min0[2]),
    .A1(M_in0[2]),
    .S(LD_alarm),
    .X(_003_[2])
  );
  sky130_fd_sc_hd__mux2_1 _470_ (
    .A0(a_min0[3]),
    .A1(M_in0[3]),
    .S(LD_alarm),
    .X(_003_[3])
  );
  sky130_fd_sc_hd__nor2b_1 _471_ (
    .A(LD_alarm),
    .B_N(a_sec0[0]),
    .Y(_005_[0])
  );
  sky130_fd_sc_hd__nor2b_1 _472_ (
    .A(LD_alarm),
    .B_N(a_sec0[1]),
    .Y(_005_[1])
  );
  sky130_fd_sc_hd__nor2b_1 _473_ (
    .A(LD_alarm),
    .B_N(a_sec0[2]),
    .Y(_005_[2])
  );
  sky130_fd_sc_hd__nor2b_1 _474_ (
    .A(LD_alarm),
    .B_N(a_sec0[3]),
    .Y(_005_[3])
  );
  sky130_fd_sc_hd__nor2_1 _475_ (
    .A(_078_),
    .B(LD_alarm),
    .Y(_006_[0])
  );
  sky130_fd_sc_hd__nor2_1 _476_ (
    .A(_079_),
    .B(LD_alarm),
    .Y(_006_[1])
  );
  sky130_fd_sc_hd__nor2b_1 _477_ (
    .A(LD_alarm),
    .B_N(a_sec1[2]),
    .Y(_006_[2])
  );
  sky130_fd_sc_hd__nor2b_1 _478_ (
    .A(LD_alarm),
    .B_N(a_sec1[3]),
    .Y(_006_[3])
  );
  sky130_fd_sc_hd__mux2_1 _479_ (
    .A0(a_hour1[0]),
    .A1(H_in1[0]),
    .S(LD_alarm),
    .X(_002_[0])
  );
  sky130_fd_sc_hd__mux2_1 _480_ (
    .A0(a_hour1[1]),
    .A1(H_in1[1]),
    .S(LD_alarm),
    .X(_002_[1])
  );
  sky130_fd_sc_hd__mux2_1 _481_ (
    .A0(a_min1[0]),
    .A1(M_in1[0]),
    .S(LD_alarm),
    .X(_004_[0])
  );
  sky130_fd_sc_hd__mux2_1 _482_ (
    .A0(a_min1[1]),
    .A1(M_in1[1]),
    .S(LD_alarm),
    .X(_004_[1])
  );
  sky130_fd_sc_hd__mux2_1 _483_ (
    .A0(a_min1[2]),
    .A1(M_in1[2]),
    .S(LD_alarm),
    .X(_004_[2])
  );
  sky130_fd_sc_hd__mux2_1 _484_ (
    .A0(a_min1[3]),
    .A1(M_in1[3]),
    .S(LD_alarm),
    .X(_004_[3])
  );
  sky130_fd_sc_hd__mux2_1 _485_ (
    .A0(a_hour0[0]),
    .A1(H_in0[0]),
    .S(LD_alarm),
    .X(_001_[0])
  );
  sky130_fd_sc_hd__mux2_1 _486_ (
    .A0(a_hour0[1]),
    .A1(H_in0[1]),
    .S(LD_alarm),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__mux2_1 _487_ (
    .A0(a_hour0[2]),
    .A1(H_in0[2]),
    .S(LD_alarm),
    .X(_001_[2])
  );
  sky130_fd_sc_hd__mux2_1 _488_ (
    .A0(a_hour0[3]),
    .A1(H_in0[3]),
    .S(LD_alarm),
    .X(_001_[3])
  );
  sky130_fd_sc_hd__nor2_1 _489_ (
    .A(_153_),
    .B(_161_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nor2_1 _490_ (
    .A(LD_time),
    .B(_225_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__or2_0 _491_ (
    .A(LD_time),
    .B(_225_),
    .X(_227_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(tmp_second[0]),
    .B(_227_),
    .Y(_011_[0])
  );
  sky130_fd_sc_hd__o21ai_0 _493_ (
    .A1(tmp_second[0]),
    .A2(tmp_second[1]),
    .B1(_226_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a21oi_1 _494_ (
    .A1(tmp_second[0]),
    .A2(tmp_second[1]),
    .B1(_228_),
    .Y(_011_[1])
  );
  sky130_fd_sc_hd__nand2_1 _495_ (
    .A(_160_),
    .B(_226_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__a31oi_1 _496_ (
    .A1(tmp_second[0]),
    .A2(tmp_second[1]),
    .A3(tmp_second[2]),
    .B1(_229_),
    .Y(_011_[2])
  );
  sky130_fd_sc_hd__a31oi_1 _497_ (
    .A1(tmp_second[0]),
    .A2(tmp_second[1]),
    .A3(tmp_second[2]),
    .B1(tmp_second[3]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__nor3_1 _498_ (
    .A(_162_),
    .B(_227_),
    .C(_230_),
    .Y(_011_[3])
  );
  sky130_fd_sc_hd__o21ai_0 _499_ (
    .A1(tmp_second[4]),
    .A2(_162_),
    .B1(_226_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__a21oi_1 _500_ (
    .A1(tmp_second[4]),
    .A2(_162_),
    .B1(_231_),
    .Y(_011_[4])
  );
  sky130_fd_sc_hd__nor2_1 _501_ (
    .A(_163_),
    .B(_227_),
    .Y(_011_[5])
  );
  sky130_fd_sc_hd__o2111ai_1 _502_ (
    .A1(tmp_minute[2]),
    .A2(_140_),
    .B1(tmp_minute[5]),
    .C1(tmp_minute[3]),
    .D1(tmp_minute[4]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__nand2_1 _503_ (
    .A(_225_),
    .B(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__mux2_1 _504_ (
    .A0(_233_),
    .A1(_225_),
    .S(tmp_minute[0]),
    .X(_234_)
  );
  sky130_fd_sc_hd__nand2_1 _505_ (
    .A(M_in0[0]),
    .B(LD_time),
    .Y(_235_)
  );
  sky130_fd_sc_hd__o21ai_0 _506_ (
    .A1(LD_time),
    .A2(_234_),
    .B1(_235_),
    .Y(_010_[0])
  );
  sky130_fd_sc_hd__nor2_1 _507_ (
    .A(LD_time),
    .B(_233_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__nor4_1 _508_ (
    .A(LD_time),
    .B(_129_),
    .C(_140_),
    .D(_233_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a221o_1 _509_ (
    .A1(LD_time),
    .A2(_104_),
    .B1(_226_),
    .B2(tmp_minute[1]),
    .C1(_237_),
    .X(_010_[1])
  );
  sky130_fd_sc_hd__nand2_1 _510_ (
    .A(_015_),
    .B(_141_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor2_1 _511_ (
    .A(_015_),
    .B(_141_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand2_1 _512_ (
    .A(_236_),
    .B(_238_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a22oi_1 _513_ (
    .A1(LD_time),
    .A2(_103_),
    .B1(_226_),
    .B2(tmp_minute[2]),
    .Y(_241_)
  );
  sky130_fd_sc_hd__o21ai_0 _514_ (
    .A1(_239_),
    .A2(_240_),
    .B1(_241_),
    .Y(_010_[2])
  );
  sky130_fd_sc_hd__nand2_1 _515_ (
    .A(LD_time),
    .B(_101_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__xnor2_1 _516_ (
    .A(_014_),
    .B(_239_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__a22oi_1 _517_ (
    .A1(tmp_minute[3]),
    .A2(_226_),
    .B1(_236_),
    .B2(_243_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nand2_1 _518_ (
    .A(_242_),
    .B(_244_),
    .Y(_010_[3])
  );
  sky130_fd_sc_hd__nor2_1 _519_ (
    .A(_132_),
    .B(_141_),
    .Y(_245_)
  );
  sky130_fd_sc_hd__nand2_1 _520_ (
    .A(tmp_minute[4]),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nand3_1 _521_ (
    .A(tmp_minute[4]),
    .B(_225_),
    .C(_245_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__a21o_1 _522_ (
    .A1(_225_),
    .A2(_245_),
    .B1(tmp_minute[4]),
    .X(_248_)
  );
  sky130_fd_sc_hd__or3_1 _523_ (
    .A(_153_),
    .B(_161_),
    .C(_232_),
    .X(_249_)
  );
  sky130_fd_sc_hd__a31oi_1 _524_ (
    .A1(_247_),
    .A2(_248_),
    .A3(_249_),
    .B1(LD_time),
    .Y(_250_)
  );
  sky130_fd_sc_hd__a21oi_1 _525_ (
    .A1(LD_time),
    .A2(_098_),
    .B1(_250_),
    .Y(_010_[4])
  );
  sky130_fd_sc_hd__xor2_1 _526_ (
    .A(_016_),
    .B(_246_),
    .X(_251_)
  );
  sky130_fd_sc_hd__a22oi_1 _527_ (
    .A1(LD_time),
    .A2(_097_),
    .B1(_236_),
    .B2(_251_),
    .Y(_252_)
  );
  sky130_fd_sc_hd__o21ai_0 _528_ (
    .A1(_077_),
    .A2(_227_),
    .B1(_252_),
    .Y(_010_[5])
  );
  sky130_fd_sc_hd__nand2_1 _529_ (
    .A(_012_),
    .B(_123_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nand3_1 _530_ (
    .A(tmp_hour[4]),
    .B(_123_),
    .C(_173_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a21oi_1 _531_ (
    .A1(_125_),
    .A2(_253_),
    .B1(tmp_hour[5]),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nand2_1 _532_ (
    .A(_254_),
    .B(_255_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _533_ (
    .A(_249_),
    .B(_256_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor3_1 _534_ (
    .A(tmp_hour[0]),
    .B(_249_),
    .C(_256_),
    .Y(_258_)
  );
  sky130_fd_sc_hd__a21oi_1 _535_ (
    .A1(tmp_hour[0]),
    .A2(_249_),
    .B1(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nand2_1 _536_ (
    .A(H_in0[0]),
    .B(LD_time),
    .Y(_260_)
  );
  sky130_fd_sc_hd__o21ai_0 _537_ (
    .A1(LD_time),
    .A2(_259_),
    .B1(_260_),
    .Y(_009_[0])
  );
  sky130_fd_sc_hd__nand3_1 _538_ (
    .A(_124_),
    .B(_174_),
    .C(_257_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__a21oi_1 _539_ (
    .A1(tmp_hour[1]),
    .A2(_249_),
    .B1(LD_time),
    .Y(_262_)
  );
  sky130_fd_sc_hd__a22oi_1 _540_ (
    .A1(LD_time),
    .A2(_122_),
    .B1(_261_),
    .B2(_262_),
    .Y(_009_[1])
  );
  sky130_fd_sc_hd__nor2_1 _541_ (
    .A(_012_),
    .B(_174_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__xnor2_1 _542_ (
    .A(_076_),
    .B(_174_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__a221oi_1 _543_ (
    .A1(tmp_hour[2]),
    .A2(_249_),
    .B1(_257_),
    .B2(_264_),
    .C1(LD_time),
    .Y(_265_)
  );
  sky130_fd_sc_hd__a21oi_1 _544_ (
    .A1(LD_time),
    .A2(_121_),
    .B1(_265_),
    .Y(_009_[2])
  );
  sky130_fd_sc_hd__xnor2_1 _545_ (
    .A(_013_),
    .B(_263_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a221oi_1 _546_ (
    .A1(tmp_hour[3]),
    .A2(_249_),
    .B1(_257_),
    .B2(_266_),
    .C1(LD_time),
    .Y(_267_)
  );
  sky130_fd_sc_hd__a21oi_1 _547_ (
    .A1(LD_time),
    .A2(_119_),
    .B1(_267_),
    .Y(_009_[3])
  );
  sky130_fd_sc_hd__nand2_1 _548_ (
    .A(tmp_hour[3]),
    .B(tmp_hour[2]),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _549_ (
    .A(_174_),
    .B(_268_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nor3_1 _550_ (
    .A(_174_),
    .B(_249_),
    .C(_268_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__a21oi_1 _551_ (
    .A1(tmp_hour[4]),
    .A2(_269_),
    .B1(_256_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__o22ai_1 _552_ (
    .A1(tmp_hour[4]),
    .A2(_270_),
    .B1(_271_),
    .B2(_249_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nand2_1 _553_ (
    .A(LD_time),
    .B(_118_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__o21ai_0 _554_ (
    .A1(LD_time),
    .A2(_272_),
    .B1(_273_),
    .Y(_009_[4])
  );
  sky130_fd_sc_hd__a32o_1 _555_ (
    .A1(tmp_hour[4]),
    .A2(_257_),
    .A3(_269_),
    .B1(tmp_hour[5]),
    .B2(_249_),
    .X(_274_)
  );
  sky130_fd_sc_hd__nor2_1 _556_ (
    .A(LD_time),
    .B(_274_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__a21oi_1 _557_ (
    .A1(LD_time),
    .A2(_117_),
    .B1(_275_),
    .Y(_009_[5])
  );
  sky130_fd_sc_hd__nand2_1 _558_ (
    .A(reset),
    .B(H_in0[0]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__or2_0 _559_ (
    .A(_075_),
    .B(_122_),
    .X(_021_)
  );
  sky130_fd_sc_hd__nand3_1 _560_ (
    .A(reset),
    .B(_113_),
    .C(_120_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__or2_0 _561_ (
    .A(_075_),
    .B(_119_),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand2_1 _562_ (
    .A(reset),
    .B(_118_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand2b_1 _563_ (
    .A_N(_117_),
    .B(reset),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nand2_1 _564_ (
    .A(reset),
    .B(M_in0[0]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _565_ (
    .A(reset),
    .B(_104_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nand2_1 _566_ (
    .A(reset),
    .B(_103_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _567_ (
    .A(reset),
    .B(_101_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__or2_0 _568_ (
    .A(_075_),
    .B(_098_),
    .X(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _569_ (
    .A(reset),
    .B(_097_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _570_ (
    .A(reset),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _571_ (
    .A(reset),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _572_ (
    .A(reset),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _573_ (
    .A(reset),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _574_ (
    .A(reset),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _575_ (
    .A(reset),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _576_ (
    .A(reset),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _577_ (
    .A(reset),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _578_ (
    .A(reset),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _579_ (
    .A(reset),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _580_ (
    .A(reset),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _581_ (
    .A(reset),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _582_ (
    .A(reset),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _583_ (
    .A(reset),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _584_ (
    .A(reset),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _585_ (
    .A(reset),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _586_ (
    .A(reset),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _587_ (
    .A(reset),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _588_ (
    .A(reset),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _589_ (
    .A(reset),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _590_ (
    .A(reset),
    .Y(_062_)
  );
  sky130_fd_sc_hd__clkinv_1 _591_ (
    .A(reset),
    .Y(_063_)
  );
  sky130_fd_sc_hd__clkinv_1 _592_ (
    .A(reset),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _593_ (
    .A(reset),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _594_ (
    .A(reset),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _595_ (
    .A(reset),
    .Y(_067_)
  );
  sky130_fd_sc_hd__clkinv_1 _596_ (
    .A(reset),
    .Y(_068_)
  );
  sky130_fd_sc_hd__clkinv_1 _597_ (
    .A(reset),
    .Y(_069_)
  );
  sky130_fd_sc_hd__clkinv_1 _598_ (
    .A(reset),
    .Y(_070_)
  );
  sky130_fd_sc_hd__clkinv_1 _599_ (
    .A(reset),
    .Y(_071_)
  );
  sky130_fd_sc_hd__clkinv_1 _600_ (
    .A(reset),
    .Y(_072_)
  );
  sky130_fd_sc_hd__clkinv_1 _601_ (
    .A(reset),
    .Y(_073_)
  );
  sky130_fd_sc_hd__clkinv_1 _602_ (
    .A(reset),
    .Y(_074_)
  );
  sky130_fd_sc_hd__dfbbp_1 _603_ (
    .CLK(clk_1s),
    .D(_009_[0]),
    .Q(tmp_hour[0]),
    .Q_N(_276_),
    .RESET_B(_018_),
    .SET_B(_019_)
  );
  sky130_fd_sc_hd__dfbbp_1 _604_ (
    .CLK(clk_1s),
    .D(_009_[1]),
    .Q(tmp_hour[1]),
    .Q_N(_017_),
    .RESET_B(_020_),
    .SET_B(_021_)
  );
  sky130_fd_sc_hd__dfbbp_1 _605_ (
    .CLK(clk_1s),
    .D(_009_[2]),
    .Q(tmp_hour[2]),
    .Q_N(_012_),
    .RESET_B(_022_),
    .SET_B(_023_)
  );
  sky130_fd_sc_hd__dfbbp_1 _606_ (
    .CLK(clk_1s),
    .D(_009_[3]),
    .Q(tmp_hour[3]),
    .Q_N(_013_),
    .RESET_B(_024_),
    .SET_B(_025_)
  );
  sky130_fd_sc_hd__dfbbp_1 _607_ (
    .CLK(clk_1s),
    .D(_009_[4]),
    .Q(tmp_hour[4]),
    .Q_N(_277_),
    .RESET_B(_026_),
    .SET_B(_027_)
  );
  sky130_fd_sc_hd__dfbbp_1 _608_ (
    .CLK(clk_1s),
    .D(_009_[5]),
    .Q(tmp_hour[5]),
    .Q_N(_278_),
    .RESET_B(_028_),
    .SET_B(_029_)
  );
  sky130_fd_sc_hd__dfbbp_1 _609_ (
    .CLK(clk_1s),
    .D(_010_[0]),
    .Q(tmp_minute[0]),
    .Q_N(_279_),
    .RESET_B(_030_),
    .SET_B(_031_)
  );
  sky130_fd_sc_hd__dfbbp_1 _610_ (
    .CLK(clk_1s),
    .D(_010_[1]),
    .Q(tmp_minute[1]),
    .Q_N(_280_),
    .RESET_B(_032_),
    .SET_B(_033_)
  );
  sky130_fd_sc_hd__dfbbp_1 _611_ (
    .CLK(clk_1s),
    .D(_010_[2]),
    .Q(tmp_minute[2]),
    .Q_N(_015_),
    .RESET_B(_034_),
    .SET_B(_035_)
  );
  sky130_fd_sc_hd__dfbbp_1 _612_ (
    .CLK(clk_1s),
    .D(_010_[3]),
    .Q(tmp_minute[3]),
    .Q_N(_014_),
    .RESET_B(_036_),
    .SET_B(_037_)
  );
  sky130_fd_sc_hd__dfbbp_1 _613_ (
    .CLK(clk_1s),
    .D(_010_[4]),
    .Q(tmp_minute[4]),
    .Q_N(_281_),
    .RESET_B(_038_),
    .SET_B(_039_)
  );
  sky130_fd_sc_hd__dfbbp_1 _614_ (
    .CLK(clk_1s),
    .D(_010_[5]),
    .Q(tmp_minute[5]),
    .Q_N(_016_),
    .RESET_B(_040_),
    .SET_B(_041_)
  );
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(clk_1s),
    .D(_000_),
    .Q(Alarm),
    .RESET_B(_042_)
  );
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(clk),
    .D(_007_),
    .Q(clk_1s),
    .RESET_B(_043_)
  );
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(clk),
    .D(_008_[0]),
    .Q(tmp_1s[0]),
    .RESET_B(_044_)
  );
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(clk),
    .D(_008_[1]),
    .Q(tmp_1s[1]),
    .RESET_B(_045_)
  );
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(clk),
    .D(_008_[2]),
    .Q(tmp_1s[2]),
    .RESET_B(_046_)
  );
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(clk),
    .D(_008_[3]),
    .Q(tmp_1s[3]),
    .RESET_B(_047_)
  );
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(clk_1s),
    .D(_011_[0]),
    .Q(tmp_second[0]),
    .RESET_B(_048_)
  );
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(clk_1s),
    .D(_011_[1]),
    .Q(tmp_second[1]),
    .RESET_B(_049_)
  );
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(clk_1s),
    .D(_011_[2]),
    .Q(tmp_second[2]),
    .RESET_B(_050_)
  );
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(clk_1s),
    .D(_011_[3]),
    .Q(tmp_second[3]),
    .RESET_B(_051_)
  );
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(clk_1s),
    .D(_011_[4]),
    .Q(tmp_second[4]),
    .RESET_B(_052_)
  );
  sky130_fd_sc_hd__dfrtp_1 _626_ (
    .CLK(clk_1s),
    .D(_011_[5]),
    .Q(tmp_second[5]),
    .RESET_B(_053_)
  );
  sky130_fd_sc_hd__dfrtp_1 _627_ (
    .CLK(clk_1s),
    .D(_002_[0]),
    .Q(a_hour1[0]),
    .RESET_B(_054_)
  );
  sky130_fd_sc_hd__dfrtp_1 _628_ (
    .CLK(clk_1s),
    .D(_002_[1]),
    .Q(a_hour1[1]),
    .RESET_B(_055_)
  );
  sky130_fd_sc_hd__dfrtp_1 _629_ (
    .CLK(clk_1s),
    .D(_001_[0]),
    .Q(a_hour0[0]),
    .RESET_B(_056_)
  );
  sky130_fd_sc_hd__dfrtp_1 _630_ (
    .CLK(clk_1s),
    .D(_001_[1]),
    .Q(a_hour0[1]),
    .RESET_B(_057_)
  );
  sky130_fd_sc_hd__dfrtp_1 _631_ (
    .CLK(clk_1s),
    .D(_001_[2]),
    .Q(a_hour0[2]),
    .RESET_B(_058_)
  );
  sky130_fd_sc_hd__dfrtp_1 _632_ (
    .CLK(clk_1s),
    .D(_001_[3]),
    .Q(a_hour0[3]),
    .RESET_B(_059_)
  );
  sky130_fd_sc_hd__dfrtp_1 _633_ (
    .CLK(clk_1s),
    .D(_004_[0]),
    .Q(a_min1[0]),
    .RESET_B(_060_)
  );
  sky130_fd_sc_hd__dfrtp_1 _634_ (
    .CLK(clk_1s),
    .D(_004_[1]),
    .Q(a_min1[1]),
    .RESET_B(_061_)
  );
  sky130_fd_sc_hd__dfrtp_1 _635_ (
    .CLK(clk_1s),
    .D(_004_[2]),
    .Q(a_min1[2]),
    .RESET_B(_062_)
  );
  sky130_fd_sc_hd__dfrtp_1 _636_ (
    .CLK(clk_1s),
    .D(_004_[3]),
    .Q(a_min1[3]),
    .RESET_B(_063_)
  );
  sky130_fd_sc_hd__dfrtp_1 _637_ (
    .CLK(clk_1s),
    .D(_003_[0]),
    .Q(a_min0[0]),
    .RESET_B(_064_)
  );
  sky130_fd_sc_hd__dfrtp_1 _638_ (
    .CLK(clk_1s),
    .D(_003_[1]),
    .Q(a_min0[1]),
    .RESET_B(_065_)
  );
  sky130_fd_sc_hd__dfrtp_1 _639_ (
    .CLK(clk_1s),
    .D(_003_[2]),
    .Q(a_min0[2]),
    .RESET_B(_066_)
  );
  sky130_fd_sc_hd__dfrtp_1 _640_ (
    .CLK(clk_1s),
    .D(_003_[3]),
    .Q(a_min0[3]),
    .RESET_B(_067_)
  );
  sky130_fd_sc_hd__dfrtp_1 _641_ (
    .CLK(clk_1s),
    .D(_006_[0]),
    .Q(a_sec1[0]),
    .RESET_B(_068_)
  );
  sky130_fd_sc_hd__dfrtp_1 _642_ (
    .CLK(clk_1s),
    .D(_006_[1]),
    .Q(a_sec1[1]),
    .RESET_B(_069_)
  );
  sky130_fd_sc_hd__dfrtp_1 _643_ (
    .CLK(clk_1s),
    .D(_006_[2]),
    .Q(a_sec1[2]),
    .RESET_B(_070_)
  );
  sky130_fd_sc_hd__dfrtp_1 _644_ (
    .CLK(clk_1s),
    .D(_006_[3]),
    .Q(a_sec1[3]),
    .RESET_B(_071_)
  );
  sky130_fd_sc_hd__dfrtp_1 _645_ (
    .CLK(clk_1s),
    .D(_005_[0]),
    .Q(a_sec0[0]),
    .RESET_B(_072_)
  );
  sky130_fd_sc_hd__dfrtp_1 _646_ (
    .CLK(clk_1s),
    .D(_005_[1]),
    .Q(a_sec0[1]),
    .RESET_B(_073_)
  );
  sky130_fd_sc_hd__dfrtp_1 _647_ (
    .CLK(clk_1s),
    .D(_005_[2]),
    .Q(a_sec0[2]),
    .RESET_B(_074_)
  );
  sky130_fd_sc_hd__dfrtp_1 _648_ (
    .CLK(clk_1s),
    .D(_005_[3]),
    .Q(a_sec0[3]),
    .RESET_B(_075_)
  );
  assign H_out0[0] = tmp_hour[0];
  assign M_out0[0] = tmp_minute[0];
  assign M_out1[3] = 1'h0;
  assign S_out0[0] = tmp_second[0];
  assign S_out1[3] = 1'h0;
  assign c_hour0 = { H_out0[3:1], tmp_hour[0] };
  assign c_hour1 = H_out1;
  assign c_min0 = { M_out0[3:1], tmp_minute[0] };
  assign c_min1 = M_out1[2:0];
  assign c_sec0 = { S_out0[3:1], tmp_second[0] };
  assign c_sec1 = { 1'h0, S_out1[2:0] };
endmodule
